[tool.poetry]
name = "systeminfo"
version = "1.0.0"
description = "Send system information in an HTTP request"
authors = ["Thinh Nguyen Phuoc <npthinh1996@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
psutil = "~6.1"
schedule = "~1.2"

[tool.poetry.group.dev.dependencies]
pyinstaller = "~6.11"
black = "~24.10"

[tool.black]
line-length = 120
target-version = ["py312"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
